//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VACIMB_Service.CIMBWebReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS", ConfigurationName="CIMBWebReference.BillPaymentServiceSoap")]
    public interface BillPaymentServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (CIMB3rdParty_InquiryRq) of message inquiryRequest does not match the default value (inquiry)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VACIMB_Service.CIMBWebReference.inquiryResponse inquiry(VACIMB_Service.CIMBWebReference.inquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<VACIMB_Service.CIMBWebReference.inquiryResponse> inquiryAsync(VACIMB_Service.CIMBWebReference.inquiryRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CIMB3rdParty_PaymentRq) of message paymentRequest does not match the default value (payment)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VACIMB_Service.CIMBWebReference.paymentResponse payment(VACIMB_Service.CIMBWebReference.paymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<VACIMB_Service.CIMBWebReference.paymentResponse> paymentAsync(VACIMB_Service.CIMBWebReference.paymentRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CIMB3rdParty_EchoRq) of message echoTestRequest does not match the default value (echoTest)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VACIMB_Service.CIMBWebReference.echoTestResponse echoTest(VACIMB_Service.CIMBWebReference.echoTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<VACIMB_Service.CIMBWebReference.echoTestResponse> echoTestAsync(VACIMB_Service.CIMBWebReference.echoTestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS")]
    public partial class InquiryRq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIDField;
        
        private string channelIDField;
        
        private string terminalIDField;
        
        private string transactionDateField;
        
        private string companyCodeField;
        
        private string customerKey1Field;
        
        private string customerKey2Field;
        
        private string customerKey3Field;
        
        private string additionalData1Field;
        
        private string additionalData2Field;
        
        private string additionalData3Field;
        
        private string additionalData4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChannelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
                this.RaisePropertyChanged("ChannelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TerminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
                this.RaisePropertyChanged("TerminalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerKey1 {
            get {
                return this.customerKey1Field;
            }
            set {
                this.customerKey1Field = value;
                this.RaisePropertyChanged("CustomerKey1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustomerKey2 {
            get {
                return this.customerKey2Field;
            }
            set {
                this.customerKey2Field = value;
                this.RaisePropertyChanged("CustomerKey2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerKey3 {
            get {
                return this.customerKey3Field;
            }
            set {
                this.customerKey3Field = value;
                this.RaisePropertyChanged("CustomerKey3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AdditionalData1 {
            get {
                return this.additionalData1Field;
            }
            set {
                this.additionalData1Field = value;
                this.RaisePropertyChanged("AdditionalData1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AdditionalData2 {
            get {
                return this.additionalData2Field;
            }
            set {
                this.additionalData2Field = value;
                this.RaisePropertyChanged("AdditionalData2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AdditionalData3 {
            get {
                return this.additionalData3Field;
            }
            set {
                this.additionalData3Field = value;
                this.RaisePropertyChanged("AdditionalData3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AdditionalData4 {
            get {
                return this.additionalData4Field;
            }
            set {
                this.additionalData4Field = value;
                this.RaisePropertyChanged("AdditionalData4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS")]
    public partial class PaymentRs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIDField;
        
        private string channelIDField;
        
        private string terminalIDField;
        
        private string transactionDateField;
        
        private string companyCodeField;
        
        private string customerKey1Field;
        
        private string customerKey2Field;
        
        private string customerKey3Field;
        
        private string paymentFlagField;
        
        private string customerNameField;
        
        private string currencyField;
        
        private int amountField;
        
        private bool amountFieldSpecified;
        
        private int feeField;
        
        private bool feeFieldSpecified;
        
        private int paidAmountField;
        
        private bool paidAmountFieldSpecified;
        
        private string referenceNumberTransactionField;
        
        private string additionalData1Field;
        
        private string additionalData2Field;
        
        private string additionalData3Field;
        
        private string additionalData4Field;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChannelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
                this.RaisePropertyChanged("ChannelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TerminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
                this.RaisePropertyChanged("TerminalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerKey1 {
            get {
                return this.customerKey1Field;
            }
            set {
                this.customerKey1Field = value;
                this.RaisePropertyChanged("CustomerKey1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustomerKey2 {
            get {
                return this.customerKey2Field;
            }
            set {
                this.customerKey2Field = value;
                this.RaisePropertyChanged("CustomerKey2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerKey3 {
            get {
                return this.customerKey3Field;
            }
            set {
                this.customerKey3Field = value;
                this.RaisePropertyChanged("CustomerKey3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PaymentFlag {
            get {
                return this.paymentFlagField;
            }
            set {
                this.paymentFlagField = value;
                this.RaisePropertyChanged("PaymentFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("AmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int Fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
                this.RaisePropertyChanged("Fee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FeeSpecified {
            get {
                return this.feeFieldSpecified;
            }
            set {
                this.feeFieldSpecified = value;
                this.RaisePropertyChanged("FeeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int PaidAmount {
            get {
                return this.paidAmountField;
            }
            set {
                this.paidAmountField = value;
                this.RaisePropertyChanged("PaidAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaidAmountSpecified {
            get {
                return this.paidAmountFieldSpecified;
            }
            set {
                this.paidAmountFieldSpecified = value;
                this.RaisePropertyChanged("PaidAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ReferenceNumberTransaction {
            get {
                return this.referenceNumberTransactionField;
            }
            set {
                this.referenceNumberTransactionField = value;
                this.RaisePropertyChanged("ReferenceNumberTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AdditionalData1 {
            get {
                return this.additionalData1Field;
            }
            set {
                this.additionalData1Field = value;
                this.RaisePropertyChanged("AdditionalData1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AdditionalData2 {
            get {
                return this.additionalData2Field;
            }
            set {
                this.additionalData2Field = value;
                this.RaisePropertyChanged("AdditionalData2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AdditionalData3 {
            get {
                return this.additionalData3Field;
            }
            set {
                this.additionalData3Field = value;
                this.RaisePropertyChanged("AdditionalData3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string AdditionalData4 {
            get {
                return this.additionalData4Field;
            }
            set {
                this.additionalData4Field = value;
                this.RaisePropertyChanged("AdditionalData4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ResponseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS")]
    public partial class PaymentRq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIDField;
        
        private string channelIDField;
        
        private string terminalIDField;
        
        private string transactionDateField;
        
        private string companyCodeField;
        
        private string customerKey1Field;
        
        private string customerKey2Field;
        
        private string customerKey3Field;
        
        private string languageField;
        
        private string currencyField;
        
        private int amountField;
        
        private bool amountFieldSpecified;
        
        private int feeField;
        
        private bool feeFieldSpecified;
        
        private int paidAmountField;
        
        private bool paidAmountFieldSpecified;
        
        private string referenceNumberTransactionField;
        
        private string flagPaymentListField;
        
        private string customerNameField;
        
        private string additionalData1Field;
        
        private string additionalData2Field;
        
        private string additionalData3Field;
        
        private string additionalData4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChannelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
                this.RaisePropertyChanged("ChannelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TerminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
                this.RaisePropertyChanged("TerminalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerKey1 {
            get {
                return this.customerKey1Field;
            }
            set {
                this.customerKey1Field = value;
                this.RaisePropertyChanged("CustomerKey1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustomerKey2 {
            get {
                return this.customerKey2Field;
            }
            set {
                this.customerKey2Field = value;
                this.RaisePropertyChanged("CustomerKey2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerKey3 {
            get {
                return this.customerKey3Field;
            }
            set {
                this.customerKey3Field = value;
                this.RaisePropertyChanged("CustomerKey3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("AmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
                this.RaisePropertyChanged("Fee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FeeSpecified {
            get {
                return this.feeFieldSpecified;
            }
            set {
                this.feeFieldSpecified = value;
                this.RaisePropertyChanged("FeeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int PaidAmount {
            get {
                return this.paidAmountField;
            }
            set {
                this.paidAmountField = value;
                this.RaisePropertyChanged("PaidAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaidAmountSpecified {
            get {
                return this.paidAmountFieldSpecified;
            }
            set {
                this.paidAmountFieldSpecified = value;
                this.RaisePropertyChanged("PaidAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ReferenceNumberTransaction {
            get {
                return this.referenceNumberTransactionField;
            }
            set {
                this.referenceNumberTransactionField = value;
                this.RaisePropertyChanged("ReferenceNumberTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FlagPaymentList {
            get {
                return this.flagPaymentListField;
            }
            set {
                this.flagPaymentListField = value;
                this.RaisePropertyChanged("FlagPaymentList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AdditionalData1 {
            get {
                return this.additionalData1Field;
            }
            set {
                this.additionalData1Field = value;
                this.RaisePropertyChanged("AdditionalData1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AdditionalData2 {
            get {
                return this.additionalData2Field;
            }
            set {
                this.additionalData2Field = value;
                this.RaisePropertyChanged("AdditionalData2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string AdditionalData3 {
            get {
                return this.additionalData3Field;
            }
            set {
                this.additionalData3Field = value;
                this.RaisePropertyChanged("AdditionalData3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string AdditionalData4 {
            get {
                return this.additionalData4Field;
            }
            set {
                this.additionalData4Field = value;
                this.RaisePropertyChanged("AdditionalData4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS")]
    public partial class BillDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string billCurrencyField;
        
        private string billCodeField;
        
        private int billAmountField;
        
        private bool billAmountFieldSpecified;
        
        private string billReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BillCurrency {
            get {
                return this.billCurrencyField;
            }
            set {
                this.billCurrencyField = value;
                this.RaisePropertyChanged("BillCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BillCode {
            get {
                return this.billCodeField;
            }
            set {
                this.billCodeField = value;
                this.RaisePropertyChanged("BillCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int BillAmount {
            get {
                return this.billAmountField;
            }
            set {
                this.billAmountField = value;
                this.RaisePropertyChanged("BillAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BillAmountSpecified {
            get {
                return this.billAmountFieldSpecified;
            }
            set {
                this.billAmountFieldSpecified = value;
                this.RaisePropertyChanged("BillAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BillReference {
            get {
                return this.billReferenceField;
            }
            set {
                this.billReferenceField = value;
                this.RaisePropertyChanged("BillReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS")]
    public partial class InquiryRs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIDField;
        
        private string channelIDField;
        
        private string terminalIDField;
        
        private string transactionDateField;
        
        private string companyCodeField;
        
        private string customerKey1Field;
        
        private string customerKey2Field;
        
        private string customerKey3Field;
        
        private BillDetail[] billDetailListField;
        
        private string currencyField;
        
        private int amountField;
        
        private bool amountFieldSpecified;
        
        private int feeField;
        
        private bool feeFieldSpecified;
        
        private int paidAmountField;
        
        private bool paidAmountFieldSpecified;
        
        private string customerNameField;
        
        private string additionalData1Field;
        
        private string additionalData2Field;
        
        private string additionalData3Field;
        
        private string additionalData4Field;
        
        private string flagPaymentField;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChannelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
                this.RaisePropertyChanged("ChannelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TerminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
                this.RaisePropertyChanged("TerminalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerKey1 {
            get {
                return this.customerKey1Field;
            }
            set {
                this.customerKey1Field = value;
                this.RaisePropertyChanged("CustomerKey1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustomerKey2 {
            get {
                return this.customerKey2Field;
            }
            set {
                this.customerKey2Field = value;
                this.RaisePropertyChanged("CustomerKey2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerKey3 {
            get {
                return this.customerKey3Field;
            }
            set {
                this.customerKey3Field = value;
                this.RaisePropertyChanged("CustomerKey3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public BillDetail[] BillDetailList {
            get {
                return this.billDetailListField;
            }
            set {
                this.billDetailListField = value;
                this.RaisePropertyChanged("BillDetailList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("AmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
                this.RaisePropertyChanged("Fee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FeeSpecified {
            get {
                return this.feeFieldSpecified;
            }
            set {
                this.feeFieldSpecified = value;
                this.RaisePropertyChanged("FeeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int PaidAmount {
            get {
                return this.paidAmountField;
            }
            set {
                this.paidAmountField = value;
                this.RaisePropertyChanged("PaidAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaidAmountSpecified {
            get {
                return this.paidAmountFieldSpecified;
            }
            set {
                this.paidAmountFieldSpecified = value;
                this.RaisePropertyChanged("PaidAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AdditionalData1 {
            get {
                return this.additionalData1Field;
            }
            set {
                this.additionalData1Field = value;
                this.RaisePropertyChanged("AdditionalData1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AdditionalData2 {
            get {
                return this.additionalData2Field;
            }
            set {
                this.additionalData2Field = value;
                this.RaisePropertyChanged("AdditionalData2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AdditionalData3 {
            get {
                return this.additionalData3Field;
            }
            set {
                this.additionalData3Field = value;
                this.RaisePropertyChanged("AdditionalData3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AdditionalData4 {
            get {
                return this.additionalData4Field;
            }
            set {
                this.additionalData4Field = value;
                this.RaisePropertyChanged("AdditionalData4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string FlagPayment {
            get {
                return this.flagPaymentField;
            }
            set {
                this.flagPaymentField = value;
                this.RaisePropertyChanged("FlagPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ResponseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CIMB3rdParty_InquiryRq", WrapperNamespace="http://CIMB3rdParty/BillPaymentWS", IsWrapped=true)]
    public partial class inquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS", Order=0)]
        public VACIMB_Service.CIMBWebReference.InquiryRq InquiryRq;
        
        public inquiryRequest() {
        }
        
        public inquiryRequest(VACIMB_Service.CIMBWebReference.InquiryRq InquiryRq) {
            this.InquiryRq = InquiryRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CIMB3rdParty_InquiryRs", WrapperNamespace="http://CIMB3rdParty/BillPaymentWS", IsWrapped=true)]
    public partial class inquiryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS", Order=0)]
        public VACIMB_Service.CIMBWebReference.InquiryRs InquiryRs;
        
        public inquiryResponse() {
        }
        
        public inquiryResponse(VACIMB_Service.CIMBWebReference.InquiryRs InquiryRs) {
            this.InquiryRs = InquiryRs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CIMB3rdParty_PaymentRq", WrapperNamespace="http://CIMB3rdParty/BillPaymentWS", IsWrapped=true)]
    public partial class paymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS", Order=0)]
        public VACIMB_Service.CIMBWebReference.PaymentRq PaymentRq;
        
        public paymentRequest() {
        }
        
        public paymentRequest(VACIMB_Service.CIMBWebReference.PaymentRq PaymentRq) {
            this.PaymentRq = PaymentRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CIMB3rdParty_PaymentRs", WrapperNamespace="http://CIMB3rdParty/BillPaymentWS", IsWrapped=true)]
    public partial class paymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS", Order=0)]
        public VACIMB_Service.CIMBWebReference.PaymentRs PaymentRs;
        
        public paymentResponse() {
        }
        
        public paymentResponse(VACIMB_Service.CIMBWebReference.PaymentRs PaymentRs) {
            this.PaymentRs = PaymentRs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CIMB3rdParty_EchoRq", WrapperNamespace="http://CIMB3rdParty/BillPaymentWS", IsWrapped=true)]
    public partial class echoTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS", Order=0)]
        public string EchoRequest;
        
        public echoTestRequest() {
        }
        
        public echoTestRequest(string EchoRequest) {
            this.EchoRequest = EchoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CIMB3rdParty_EchoRs", WrapperNamespace="http://CIMB3rdParty/BillPaymentWS", IsWrapped=true)]
    public partial class echoTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIMB3rdParty/BillPaymentWS", Order=0)]
        public string EchoResponse;
        
        public echoTestResponse() {
        }
        
        public echoTestResponse(string EchoResponse) {
            this.EchoResponse = EchoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BillPaymentServiceSoapChannel : VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillPaymentServiceSoapClient : System.ServiceModel.ClientBase<VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap>, VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap {
        
        public BillPaymentServiceSoapClient() {
        }
        
        public BillPaymentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillPaymentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillPaymentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillPaymentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VACIMB_Service.CIMBWebReference.inquiryResponse VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap.inquiry(VACIMB_Service.CIMBWebReference.inquiryRequest request) {
            return base.Channel.inquiry(request);
        }
        
        public VACIMB_Service.CIMBWebReference.InquiryRs inquiry(VACIMB_Service.CIMBWebReference.InquiryRq InquiryRq) {
            VACIMB_Service.CIMBWebReference.inquiryRequest inValue = new VACIMB_Service.CIMBWebReference.inquiryRequest();
            inValue.InquiryRq = InquiryRq;
            VACIMB_Service.CIMBWebReference.inquiryResponse retVal = ((VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap)(this)).inquiry(inValue);
            return retVal.InquiryRs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VACIMB_Service.CIMBWebReference.inquiryResponse> VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap.inquiryAsync(VACIMB_Service.CIMBWebReference.inquiryRequest request) {
            return base.Channel.inquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<VACIMB_Service.CIMBWebReference.inquiryResponse> inquiryAsync(VACIMB_Service.CIMBWebReference.InquiryRq InquiryRq) {
            VACIMB_Service.CIMBWebReference.inquiryRequest inValue = new VACIMB_Service.CIMBWebReference.inquiryRequest();
            inValue.InquiryRq = InquiryRq;
            return ((VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap)(this)).inquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VACIMB_Service.CIMBWebReference.paymentResponse VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap.payment(VACIMB_Service.CIMBWebReference.paymentRequest request) {
            return base.Channel.payment(request);
        }
        
        public VACIMB_Service.CIMBWebReference.PaymentRs payment(VACIMB_Service.CIMBWebReference.PaymentRq PaymentRq) {
            VACIMB_Service.CIMBWebReference.paymentRequest inValue = new VACIMB_Service.CIMBWebReference.paymentRequest();
            inValue.PaymentRq = PaymentRq;
            VACIMB_Service.CIMBWebReference.paymentResponse retVal = ((VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap)(this)).payment(inValue);
            return retVal.PaymentRs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VACIMB_Service.CIMBWebReference.paymentResponse> VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap.paymentAsync(VACIMB_Service.CIMBWebReference.paymentRequest request) {
            return base.Channel.paymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<VACIMB_Service.CIMBWebReference.paymentResponse> paymentAsync(VACIMB_Service.CIMBWebReference.PaymentRq PaymentRq) {
            VACIMB_Service.CIMBWebReference.paymentRequest inValue = new VACIMB_Service.CIMBWebReference.paymentRequest();
            inValue.PaymentRq = PaymentRq;
            return ((VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap)(this)).paymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VACIMB_Service.CIMBWebReference.echoTestResponse VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap.echoTest(VACIMB_Service.CIMBWebReference.echoTestRequest request) {
            return base.Channel.echoTest(request);
        }
        
        public string echoTest(string EchoRequest) {
            VACIMB_Service.CIMBWebReference.echoTestRequest inValue = new VACIMB_Service.CIMBWebReference.echoTestRequest();
            inValue.EchoRequest = EchoRequest;
            VACIMB_Service.CIMBWebReference.echoTestResponse retVal = ((VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap)(this)).echoTest(inValue);
            return retVal.EchoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VACIMB_Service.CIMBWebReference.echoTestResponse> VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap.echoTestAsync(VACIMB_Service.CIMBWebReference.echoTestRequest request) {
            return base.Channel.echoTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<VACIMB_Service.CIMBWebReference.echoTestResponse> echoTestAsync(string EchoRequest) {
            VACIMB_Service.CIMBWebReference.echoTestRequest inValue = new VACIMB_Service.CIMBWebReference.echoTestRequest();
            inValue.EchoRequest = EchoRequest;
            return ((VACIMB_Service.CIMBWebReference.BillPaymentServiceSoap)(this)).echoTestAsync(inValue);
        }
    }
}
